Create and style a calculator
cyrilmuchemi/Math-Magicians pull request #2
Opened 2022-06-28 15:32 UTC by cyrilmuchemi

### Project requirements

In the previous project, you worked on the setup of a React application using Create React App (CRA), now you should:

- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called `components`.
- Inside `components`, create a new `Calculator.js` file.
- In `Calculator.js`, create a React component that matches this design:

<p align="center">
  <img src="./images/calculator.png" alt="Calculator" width="300px" />
</p>

- Don't add any extra design.
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class based components (All components should be class-based).
- Once the Calculator is ready, import it and use it in your main component (App.js).
- Test it in the browser; it should render without problems.

2022-06-28 15:54 UTC, BenMukebo requested changes
### Hi @cyrilmuchemi,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Gitflow was correctly used.  ✔️   
- Professional README ✔️   
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] All the boilerplate that got created by the CRA (texts, images, and styles) ought to have gotten deleted. Kindly remove the App.test.js, reportWebVitals.js, setupTests.js... from your repo 👨🏻‍🎨 
 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly, get used to committing your code, A Git Commit Message helps identify all the changes in the documentation. When code is committed often, GIT can actually be more useful and can help you know what changes you have made for each step towards the complete feature. I would commit often and early, especially if you're on a team. Lack of commitment can often cause problems in fixing errors and putting more work into fixing them.



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 15:54 UTC, BenMukebo commented on src/App.js
>  }
- [ ] Great job so far 👏🏻 However in this milestone, you are required to implement a class-based component for your App.js instead of a stateless function component. Kindly rectify the `App.js` to be a class-based component 😄

2022-06-28 15:58 UTC, BenMukebo requested changes

2022-06-28 15:58 UTC, BenMukebo commented on src/App.css
> +
- [ ] The `Calculator.js` component should match the following given design 👇🏻 , kindly improve this 🎨 🖌️ 

||      Your Design      ||       ORginal Design       ||
|-|----------------------|-| ----------------------|-|
||![imrov](https://user-images.githubusercontent.com/79058364/176225622-16b7dc74-f2e1-4fad-b72f-a4b7247c0069.png)||![improve](https://user-images.githubusercontent.com/79058364/176225728-606cc498-453e-4a77-8082-7634675532df.png)
||

2022-06-29 06:49 UTC, FrederickMih requested changes
Hi @cyrilmuchemi , 

![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 06:49 UTC, FrederickMih commented on src/App.js
> +/* eslint-disable-next-line react/prefer-stateless-function */
- [ ] Hi @cyrilmuchemi, we are not permitted to disable Linters. Linters are great tools that flag out programming bugs and stylistic issues. You are recommended to fix these issues.
- [ ] You have also done the same thing in the `Calculator` component. Kindly fix them.
- **Hint**: I guess you are trying to make a way through the class-based component. I will advise you to go with React Pure component. [ReadMore](https://www.geeksforgeeks.org/reactjs-pure-components/)

2022-06-29 07:28 UTC, FrederickMih commented on src/App.js
> +/* eslint-disable-next-line react/prefer-stateless-function */
@ Hi @cyrilmuchemi, I sent you a link to resolve this issue. Seems you didn't open the link. Example

```.js
export default class App extends React.PureComponent{
   render(){
      return <h1>blablabla</h1>;
   }
}
```

In that example, App is still a class-based component

2022-06-29 07:38 UTC, cyrilmuchemi commented on src/App.js
> +/* eslint-disable-next-line react/prefer-stateless-function */
Oh. Thanks @FrederickMih

2022-06-29 07:53 UTC, OLIPLICHE approved these changes
Hi @cyrilmuchemi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 07:56 UTC, merged